name: very_good_slide_puzzle
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  gap: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  rive: ^0.8.1
  hovering: ^1.0.4
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  random_string: ^2.3.1
  progress_dialog_null_safe: ^1.0.7

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/
    - assets/images/folder1/
    - assets/images/folder2/
    - assets/images/folder3/

    
